<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="23557" started-at="2017-12-03T08:53:44Z" finished-at="2017-12-03T08:54:08Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="23557" started-at="2017-12-03T08:53:44Z" finished-at="2017-12-03T08:54:08Z">
      <class name="scripts.TestLogin">
        <test-method status="PASS" signature="openApplication()[pri:0, instance:scripts.TestLogin@20e2cbe0]" name="openApplication" is-config="true" duration-ms="12365" started-at="2017-12-03T14:23:45Z" finished-at="2017-12-03T14:23:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="testlogin()[pri:0, instance:scripts.TestLogin@20e2cbe0]" name="testlogin" duration-ms="10757" started-at="2017-12-03T14:23:57Z" finished-at="2017-12-03T14:24:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [actiTime12-Enter Time-tracker123] but found [actiTIME - Enter Time-Track]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [actiTime12-Enter Time-tracker123] but found [actiTIME - Enter Time-Track]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at scripts.TestLogin.testlogin(TestLogin.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testlogin -->
        <test-method status="PASS" signature="closeApplication()[pri:0, instance:scripts.TestLogin@20e2cbe0]" name="closeApplication" is-config="true" duration-ms="0" started-at="2017-12-03T14:24:08Z" finished-at="2017-12-03T14:24:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- scripts.TestLogin -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
